# Generated by Django 6.0.3 on 2026-05-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detalheconsulta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dono',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={'managed': False},
        ),
    ]
