# Generated by Django 6.0.3 on 2026-05-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_animal_options_alter_consulta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animal',
            table='animal',
        ),
        migrations.AlterModelTable(
            name='consulta',
            table='consulta',
        ),
        migrations.AlterModelTable(
            name='detalheconsulta',
            table='detalheconsulta',
        ),
        migrations.AlterModelTable(
            name='dono',
            table='dono',
        ),
        migrations.AlterModelTable(
            name='medicamento',
            table='medicamento',
        ),
        migrations.AlterModelTable(
            name='servico',
            table='servico',
        ),
        migrations.AlterModelTable(
            name='veterinario',
            table='veterinario',
        ),
    ]
